baseURL = "http://example.org/"
languageCode = "es-ES"
title = "Trangalladas"
theme = "ananke"

[params]
  favicon = ""
  site_logo = ""
  description = "Un blog de trangalladas e iso."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  
##Apariencia 
 featured_image =  "/images/venta.jpg"
 background_color_class = "bg-black"
